-- Create database and tables for the ecommerce app
CREATE DATABASE IF NOT EXISTS ecommerce;
USE ecommerce;

-- Products
CREATE TABLE IF NOT EXISTS products (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255),
  description TEXT,
  price DECIMAL(10,2),
  image_url VARCHAR(500),
  category VARCHAR(100),
  stock INT DEFAULT 0
);

-- Users
CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255),
  email VARCHAR(255) UNIQUE,
  password VARCHAR(255),
  address TEXT,
  phone VARCHAR(20)
);

-- Orders
CREATE TABLE IF NOT EXISTS orders (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT,
  total_amount DECIMAL(10,2),
  status VARCHAR(50),
  address TEXT,
  order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Order items
CREATE TABLE IF NOT EXISTS order_items (
  id INT PRIMARY KEY AUTO_INCREMENT,
  order_id INT,
  product_id INT,
  quantity INT,
  price DECIMAL(10,2),
  FOREIGN KEY (order_id) REFERENCES orders(id),
  FOREIGN KEY (product_id) REFERENCES products(id)
);

-- Cart
CREATE TABLE IF NOT EXISTS cart (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT,
  product_id INT,
  quantity INT,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (product_id) REFERENCES products(id)
);

-- Demo data
INSERT INTO products (name, description, price, image_url, category, stock) VALUES
('Red T-Shirt', 'Comfortable cotton t-shirt', 14.99, 'https://picsum.photos/seed/redshirt/600/400', 'Clothing', 50),
('Blue Jeans', 'Slim fit denim jeans', 39.99, 'https://picsum.photos/seed/bluejeans/600/400', 'Clothing', 35),
('Wireless Headphones', 'Noise-cancelling over-ear headphones', 79.99, 'https://picsum.photos/seed/headphones/600/400', 'Electronics', 20),
('Sneakers', 'Lightweight running shoes', 49.99, 'https://picsum.photos/seed/sneakers/600/400', 'Footwear', 40),
('Coffee Maker', 'Brew perfect coffee every morning', 59.99, 'https://picsum.photos/seed/coffeemaker/600/400', 'Home', 15);

-- Demo user (email: demo@example.com / password: password)
-- Password hash for 'password' generated by bcrypt (10 rounds).
INSERT INTO users (name, email, password, address, phone) VALUES
('Demo User', 'demo@example.com', '$2a$10$OQYl7U7g7J8pWk4KpYwU3e5agGm1G2W2T3y8gXWwzF1Dq4tB3h7yS', '123 Demo Street', '000-0000000');
